---
- hosts: local
  become: yes
  vars_prompt:
      name: "username"
      prompt: "What is your name ?"
  tasks:
    - name: Install httpd
      yum: name=httpd state=latest
    - name: start httpd service
      service: name=httpd state=restarted
    - name: Copy the website config file
      template: src=index.html dest=/var/www/html/index.html
      notify:
        - Apache Restart
  handlers:
    - name: Apache Restart
      service: name=httpd state=restarted
